breadcrumb_iterator: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
permalink: none
domain: vesperin.com
highlighter: rouge

rdiscount:
  extensions:
    - footnotes     # footnotes
    - smart         # typographic substitutions with SmartyPants